name: CommandPointsMunificent
main: pgDev.bukkit.CPMunificent.CPMMain
version: 0.2
author: PG Dev Team
authors: [Devil Boy]
description: Generously grant CommandPoints over time!
depend: [CommandPoints]

permissions:
    cpmunificent.beneficiary:
        default: true
        description: Receives commandpoints.